import type { ExplorerCaseState } from "./cases/types";

// Display copy belongs to the Explorer. Manifest IDs, public exports and route
// fragments stay stable and are always retained in the search index.
export const explorerFamilyChineseLabels: Readonly<Record<string, string>> = {
  color: "颜色与主题",
  locale: "语言与地区",
  typography: "字体与排版",
  spacing: "间距规范",
  radius: "圆角规范",
  surface: "表面与边框",
  icons: "图标规范",
  motion: "动效规范",
  "z-index": "层级规范",
  density: "密度规范",
  responsive: "响应式栅格",
  "responsive-visibility": "响应式显隐",
  layout: "基础布局",
  divider: "分割线",
  scroll: "滚动区域",
  resizable: "可调整分栏",
  sticky: "吸顶操作栏",
  collapse: "折叠面板",
  aspect: "宽高比容器",
  focus: "焦点规范",
  "focus-trap": "焦点限制",
  "visually-hidden": "视觉隐藏",
  drag: "文件拖放",
  sortable: "拖动排序",
  keyboard: "键盘快捷键",
  clipboard: "复制按钮",
  overflow: "文本省略与展开",
  portal: "跨层渲染",
  button: "按钮",
  link: "链接",
  "icon-button": "图标按钮",
  "button-group": "按钮组",
  "split-button": "分裂按钮",
  "toggle-button": "切换按钮",
  toolbar: "工具栏",
  "filter-bar": "筛选栏",
  form: "表单",
  field: "表单字段",
  "text-input": "文本与密码输入",
  "search-input": "搜索输入框",
  textarea: "多行文本框",
  number: "数字输入框",
  otp: "验证码输入",
  upload: "文件上传",
  "markdown-editor": "文本编辑器",
  "code-editor": "代码编辑器",
  "inline-edit": "行内编辑",
  checkbox: "复选框",
  radio: "单选框",
  switch: "开关",
  segmented: "分段选择",
  select: "下拉选择",
  combobox: "组合输入与补全",
  "multi-select": "多项选择",
  "tag-input": "标签输入",
  cascader: "级联选择",
  "tree-select": "树形选择",
  transfer: "穿梭选择",
  slider: "滑块",
  rating: "评分",
  "color-picker": "颜色选择",
  "date-time": "日期与时间",
  "app-navigation": "应用导航",
  breadcrumb: "面包屑导航",
  tabs: "标签页",
  menu: "菜单",
  pagination: "分页",
  "load-more": "加载更多",
  "infinite-scroll": "无限滚动",
  stepper: "步骤导航",
  command: "命令面板",
  anchor: "锚点导航",
  list: "列表与虚拟列表",
  description: "描述列表",
  card: "卡片",
  tree: "树形列表",
  accordion: "手风琴折叠",
  timeline: "时间线",
  calendar: "日历",
  scheduler: "日程安排",
  statistic: "统计数值",
  chart: "柱状图",
  "code-block": "代码展示",
  meter: "计量条",
  avatar: "头像与头像组",
  tag: "标签",
  badge: "徽标",
  status: "状态指示",
  media: "图片与媒体",
  attachment: "附件",
  gallery: "图片库",
  carousel: "轮播",
  "data-table": "数据与树形表格",
  "inline-message": "行内消息",
  alert: "警告提示",
  banner: "横幅提示",
  toast: "轻提示",
  spinner: "加载指示",
  progress: "进度条与进度环",
  skeleton: "骨架屏",
  result: "结果与异常状态",
  "validation-summary": "校验摘要",
  tooltip: "文字提示",
  popover: "气泡浮层",
  "hover-card": "悬停卡片",
  dialog: "对话框与确认弹窗",
  popconfirm: "气泡确认",
  drawer: "抽屉",
  lightbox: "图片预览",
  tour: "操作引导",
  authentication: "认证与品牌登录",
  "list-filter": "列表与筛选页面",
  "create-edit": "新建与编辑页面",
  detail: "详情页面",
  settings: "设置页面",
  wizard: "分步流程",
  "master-detail": "主从详情布局",
  "import-export": "导入与导出页面",
  "status-page": "状态页面",
};

const foundationEnglishLabels: Readonly<Record<string, string>> = {
  typography: "Typography",
  spacing: "Spacing",
  radius: "Radius",
  surface: "Surface",
  icons: "Icons",
  motion: "Motion",
  "z-index": "Z-index",
  density: "Density",
  focus: "Focus",
};

export function explorerFamilyLabels(id: string, publicExports: readonly string[]) {
  const chineseLabel = explorerFamilyChineseLabels[id];
  if (!chineseLabel) throw new Error(`Explorer family ${id} is missing its Chinese label.`);
  const englishLabel = publicExports.join(" / ") || foundationEnglishLabels[id];
  if (!englishLabel) throw new Error(`Explorer family ${id} is missing its English display name.`);
  return {
    chineseLabel,
    englishLabel,
    label: `${chineseLabel} · ${englishLabel}`,
  };
}

export const explorerStateLabels = {
  default: "默认",
  disabled: "禁用",
  readOnly: "只读",
  controlled: "受控",
  uncontrolled: "非受控",
  loading: "加载中",
  empty: "空数据",
  error: "错误",
  validation: "校验",
  longContent: "长内容",
  keyboard: "键盘操作",
  mobile: "移动端",
  overlay: "浮层交互",
  dark: "深色模式",
  locale: "多语言",
  usage: "使用方式",
} as const satisfies Readonly<Record<ExplorerCaseState, string>>;

export function formatStateLabel(state: ExplorerCaseState): string {
  return explorerStateLabels[state];
}
