// @personal-ui-coverage {"kind":"a11y","runner":"a11y","exports":["Accordion","Alert","AnchorNavigation","AppNavigation","AsyncAction","AsyncSelect","Attachment","AuthenticationPage","Autocomplete","Avatar","AvatarGroup","Badge","Banner","BarChart","BottomNavigation","Breadcrumbs","Button","ButtonGroup","Calendar","Carousel","Cascader","Checkbox","ClipboardButton","CodeBlock","CodeEditor","Collapse","ColorPicker","Combobox","CommandPalette","ConfirmDialog","ContextMenu","CreateEditPage","DataTable","DateField","DateRangeField","DescriptionList","DetailPage","Dialog","DragDrop","Drawer","DropdownMenu","EmptyState","ErrorState","ExpandableText","FamilyLoginPage","Field","FileUpload","FilterBar","FocusTrap","Form","Gallery","GuidedTour","HoverCard","IconButton","ImportExportPage","InfiniteScroll","InlineEdit","InlineMessage","Input","Lightbox","Link","ListManagementPage","LoadMore","MarkdownEditor","MasterDetail","Media","MemberManagementPage","Menu","Meter","MultiSelect","NoResults","NumberInput","OtpInput","OverflowText","PageHeading","Pagination","PasswordInput","Popconfirm","Popover","Progress","ProgressRing","Radio","Rating","ResizablePanels","RetryButton","RichTextEditor","Scheduler","SearchableSelect","SearchFilterPage","SearchInput","SegmentedControl","Select","SettingsPage","SideNavigation","Slider","SortableList","Spinner","SplitButton","Statistic","StatusIndicator","StatusPage","Stepper","Switch","Tabs","Tag","TagInput","Textarea","Timeline","TimezoneSelect","ToastProvider","ToggleButton","Toolbar","Tooltip","TopNavigation","Transfer","Tree","TreeSelect","TreeTable","ValidationSummary","WizardFlow"]}
import { registerAriaEvidence, type AriaEvidenceCase } from "../support/m6-evidence";

const ariaEvidenceCases = [
  { exportName: "Accordion", family: "accordion", category: "data" },
  { exportName: "Alert", family: "alert", category: "feedback" },
  { exportName: "AnchorNavigation", family: "anchor", category: "navigation" },
  { exportName: "AppNavigation", family: "app-navigation", category: "navigation" },
  { exportName: "AsyncAction", family: "result", category: "feedback" },
  { exportName: "AsyncSelect", family: "select", category: "input" },
  { exportName: "Attachment", family: "attachment", category: "data" },
  { exportName: "AuthenticationPage", family: "authentication", category: "pattern", prepare: { action: "click", role: "tab", name: "通用认证页" } },
  { exportName: "Autocomplete", family: "combobox", category: "input" },
  { exportName: "Avatar", family: "avatar", category: "data" },
  { exportName: "AvatarGroup", family: "avatar", category: "data" },
  { exportName: "Badge", family: "badge", category: "data" },
  { exportName: "Banner", family: "banner", category: "feedback" },
  { exportName: "BarChart", family: "chart", category: "data" },
  { exportName: "BottomNavigation", family: "app-navigation", category: "navigation" },
  { exportName: "Breadcrumbs", family: "breadcrumb", category: "navigation" },
  { exportName: "Button", family: "button", category: "actions" },
  { exportName: "ButtonGroup", family: "button-group", category: "actions" },
  { exportName: "Calendar", family: "calendar", category: "data" },
  { exportName: "Carousel", family: "carousel", category: "data" },
  { exportName: "Cascader", family: "cascader", category: "input" },
  { exportName: "Checkbox", family: "checkbox", category: "input" },
  { exportName: "ClipboardButton", family: "clipboard", category: "actions" },
  { exportName: "CodeBlock", family: "code-block", category: "data" },
  { exportName: "CodeEditor", family: "code-editor", category: "input" },
  { exportName: "Collapse", family: "collapse", category: "data" },
  { exportName: "ColorPicker", family: "color-picker", category: "input" },
  { exportName: "Combobox", family: "combobox", category: "input" },
  { exportName: "CommandPalette", family: "command", category: "navigation", ownerScope: "page", prepare: { action: "click", role: "button", name: "打开命令面板" } },
  { exportName: "ConfirmDialog", family: "dialog", category: "overlay", ownerName: "Dialog", ownerScope: "page", prepare: { action: "click", role: "button", name: "删除项目" } },
  { exportName: "ContextMenu", family: "menu", category: "navigation" },
  { exportName: "CreateEditPage", family: "create-edit", category: "pattern" },
  { exportName: "DataTable", family: "data-table", category: "data" },
  { exportName: "DateField", family: "date-time", category: "input" },
  { exportName: "DateRangeField", family: "date-time", category: "input" },
  { exportName: "DescriptionList", family: "description", category: "data" },
  { exportName: "DetailPage", family: "detail", category: "pattern" },
  { exportName: "Dialog", family: "dialog", category: "overlay", ownerScope: "page", prepare: { action: "click", role: "button", name: "编辑项目" } },
  { exportName: "DragDrop", family: "drag", category: "actions" },
  { exportName: "Drawer", family: "drawer", category: "overlay", ownerScope: "page", prepare: { action: "click", role: "button", name: "打开成员详情" } },
  { exportName: "DropdownMenu", family: "menu", category: "navigation" },
  { exportName: "EmptyState", family: "result", category: "feedback" },
  { exportName: "ErrorState", family: "result", category: "feedback" },
  { exportName: "ExpandableText", family: "overflow", category: "data" },
  { exportName: "FamilyLoginPage", family: "authentication", category: "pattern" },
  { exportName: "Field", family: "field", category: "input" },
  { exportName: "FileUpload", family: "upload", category: "input" },
  { exportName: "FilterBar", family: "filter-bar", category: "actions" },
  { exportName: "FocusTrap", family: "focus-trap", category: "foundation" },
  { exportName: "Form", family: "form", category: "input" },
  { exportName: "Gallery", family: "gallery", category: "data" },
  { exportName: "GuidedTour", family: "tour", category: "overlay", ownerScope: "page", prepare: { action: "click", role: "button", name: "开始引导" } },
  { exportName: "HoverCard", family: "hover-card", category: "overlay", prepare: { action: "focus", role: "button", name: "林夏的资料卡" } },
  { exportName: "IconButton", family: "icon-button", category: "actions" },
  { exportName: "ImportExportPage", family: "import-export", category: "pattern" },
  { exportName: "InfiniteScroll", family: "infinite-scroll", category: "navigation" },
  { exportName: "InlineEdit", family: "inline-edit", category: "input" },
  { exportName: "InlineMessage", family: "inline-message", category: "feedback" },
  { exportName: "Input", family: "text-input", category: "input" },
  { exportName: "Lightbox", family: "lightbox", category: "overlay", ownerScope: "page", prepare: { action: "click", role: "button", name: "预览图片" } },
  { exportName: "Link", family: "link", category: "actions" },
  { exportName: "ListManagementPage", family: "list-filter", category: "pattern" },
  { exportName: "LoadMore", family: "load-more", category: "navigation" },
  { exportName: "MarkdownEditor", family: "markdown-editor", category: "input" },
  { exportName: "MasterDetail", family: "master-detail", category: "pattern" },
  { exportName: "Media", family: "media", category: "data" },
  { exportName: "MemberManagementPage", family: "list-filter", category: "pattern", prepare: { action: "click", role: "tab", name: "成员工作流" } },
  { exportName: "Menu", family: "menu", category: "navigation" },
  { exportName: "Meter", family: "meter", category: "data" },
  { exportName: "MultiSelect", family: "multi-select", category: "input" },
  { exportName: "NoResults", family: "result", category: "feedback" },
  { exportName: "NumberInput", family: "number", category: "input" },
  { exportName: "OtpInput", family: "otp", category: "input" },
  { exportName: "OverflowText", family: "overflow", category: "data" },
  { exportName: "PageHeading", family: "list-filter", category: "pattern" },
  { exportName: "Pagination", family: "pagination", category: "navigation" },
  { exportName: "PasswordInput", family: "text-input", category: "input" },
  { exportName: "Popconfirm", family: "popconfirm", category: "overlay", ownerScope: "page", prepare: { action: "click", role: "button", name: "确认移除成员" } },
  { exportName: "Popover", family: "popover", category: "overlay", prepare: { action: "click", role: "button", name: "筛选摘要" } },
  { exportName: "Progress", family: "progress", category: "feedback" },
  { exportName: "ProgressRing", family: "progress", category: "feedback" },
  { exportName: "Radio", family: "radio", category: "input" },
  { exportName: "Rating", family: "rating", category: "input" },
  { exportName: "ResizablePanels", family: "resizable", category: "foundation" },
  { exportName: "RetryButton", family: "result", category: "feedback" },
  { exportName: "RichTextEditor", family: "markdown-editor", category: "input" },
  { exportName: "Scheduler", family: "scheduler", category: "data" },
  { exportName: "SearchableSelect", family: "select", category: "input" },
  { exportName: "SearchFilterPage", family: "list-filter", category: "pattern", prepare: { action: "click", role: "tab", name: "搜索筛选" } },
  { exportName: "SearchInput", family: "search-input", category: "input" },
  { exportName: "SegmentedControl", family: "segmented", category: "input" },
  { exportName: "Select", family: "select", category: "input" },
  { exportName: "SettingsPage", family: "settings", category: "pattern" },
  { exportName: "SideNavigation", family: "app-navigation", category: "navigation" },
  { exportName: "Slider", family: "slider", category: "input" },
  { exportName: "SortableList", family: "sortable", category: "actions" },
  { exportName: "Spinner", family: "spinner", category: "feedback" },
  { exportName: "SplitButton", family: "split-button", category: "actions" },
  { exportName: "Statistic", family: "statistic", category: "data" },
  { exportName: "StatusIndicator", family: "status", category: "data" },
  { exportName: "StatusPage", family: "status-page", category: "pattern" },
  { exportName: "Stepper", family: "stepper", category: "navigation" },
  { exportName: "Switch", family: "switch", category: "input" },
  { exportName: "Tabs", family: "tabs", category: "navigation" },
  { exportName: "Tag", family: "tag", category: "data" },
  { exportName: "TagInput", family: "tag-input", category: "input" },
  { exportName: "Textarea", family: "textarea", category: "input" },
  { exportName: "Timeline", family: "timeline", category: "data" },
  { exportName: "TimezoneSelect", family: "date-time", category: "input" },
  { exportName: "ToastProvider", family: "toast", category: "feedback", ownerScope: "page", prepare: { action: "click", role: "button", name: "居中成功提示" } },
  { exportName: "ToggleButton", family: "toggle-button", category: "actions" },
  { exportName: "Toolbar", family: "toolbar", category: "actions" },
  { exportName: "Tooltip", family: "tooltip", category: "overlay", prepare: { action: "focus", role: "button", name: "悬停或聚焦" } },
  { exportName: "TopNavigation", family: "app-navigation", category: "navigation" },
  { exportName: "Transfer", family: "transfer", category: "input" },
  { exportName: "Tree", family: "tree", category: "data" },
  { exportName: "TreeSelect", family: "tree-select", category: "input" },
  { exportName: "TreeTable", family: "data-table", category: "data" },
  { exportName: "ValidationSummary", family: "validation-summary", category: "feedback" },
  { exportName: "WizardFlow", family: "wizard", category: "pattern" },
] as const satisfies readonly AriaEvidenceCase[];

registerAriaEvidence(ariaEvidenceCases);
