// @personal-ui-coverage {"kind":"keyboard","runner":"browser","exports":["Accordion","AnchorNavigation","AppNavigation","AsyncAction","AsyncSelect","Attachment","AuthenticationPage","Autocomplete","BottomNavigation","Breadcrumbs","Button","Calendar","Carousel","Cascader","Checkbox","ClipboardButton","CodeBlock","CodeEditor","Collapse","ColorPicker","Combobox","CommandPalette","ConfirmDialog","ContextMenu","CreateEditPage","DataTable","DateField","DateRangeField","DetailPage","Dialog","DragDrop","Drawer","DropdownMenu","ExpandableText","FamilyLoginPage","FileUpload","FilterBar","FocusTrap","Form","Gallery","GuidedTour","HoverCard","IconButton","ImportExportPage","InfiniteScroll","InlineEdit","Input","Lightbox","Link","ListManagementPage","LoadMore","MarkdownEditor","MasterDetail","MemberManagementPage","Menu","MultiSelect","NumberInput","OtpInput","OverflowText","PageHeading","Pagination","PasswordInput","Popconfirm","Popover","Radio","Rating","ResizablePanels","RetryButton","RichTextEditor","Scheduler","SearchableSelect","SearchFilterPage","SearchInput","SegmentedControl","Select","SettingsPage","SideNavigation","Slider","SortableList","SplitButton","StatusPage","Stepper","Switch","Tabs","Tag","TagInput","Textarea","TimezoneSelect","ToastProvider","ToggleButton","Toolbar","Tooltip","TopNavigation","Transfer","Tree","TreeSelect","TreeTable","useCommandPaletteShortcut","ValidationSummary","WizardFlow"]}
import { registerKeyboardEvidence, type KeyboardEvidenceCase } from "../support/m6-evidence";

const keyboardEvidenceCases = [
  { exportName: "Accordion", family: "accordion", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "AnchorNavigation", family: "anchor", category: "navigation", strategy: "native-activate" },
  { exportName: "AppNavigation", family: "app-navigation", category: "navigation", strategy: "native-activate" },
  { exportName: "AsyncAction", family: "result", category: "feedback", strategy: "native-activate" },
  { exportName: "AsyncSelect", family: "select", category: "input", strategy: "open-close", key: "Enter", targetRole: "combobox" },
  { exportName: "Attachment", family: "attachment", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "AuthenticationPage", family: "authentication", category: "pattern", strategy: "tab", prepare: { action: "click", role: "tab", name: "通用认证页" } },
  { exportName: "Autocomplete", family: "combobox", category: "input", strategy: "open-close", targetRole: "combobox" },
  { exportName: "BottomNavigation", family: "app-navigation", category: "navigation", strategy: "native-activate" },
  { exportName: "Breadcrumbs", family: "breadcrumb", category: "navigation", strategy: "native-activate" },
  { exportName: "Button", family: "button", category: "actions", strategy: "native-activate" },
  { exportName: "Calendar", family: "calendar", category: "data", strategy: "arrow-change", key: "ArrowRight", targetSelector: "button[tabindex='0']" },
  { exportName: "Carousel", family: "carousel", category: "data", strategy: "native-activate", targetRole: "button", targetName: "下一项" },
  { exportName: "Cascader", family: "cascader", category: "input", strategy: "open-close", targetRole: "combobox" },
  { exportName: "Checkbox", family: "checkbox", category: "input", strategy: "toggle", targetSelector: "input[type='checkbox']" },
  { exportName: "ClipboardButton", family: "clipboard", category: "actions", strategy: "native-activate" },
  { exportName: "CodeBlock", family: "code-block", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "CodeEditor", family: "code-editor", category: "input", strategy: "type" },
  { exportName: "Collapse", family: "collapse", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "ColorPicker", family: "color-picker", category: "input", strategy: "native-activate", targetSelector: "button:not(:disabled)" },
  { exportName: "Combobox", family: "combobox", category: "input", strategy: "open-close", targetRole: "combobox" },
  { exportName: "CommandPalette", family: "command", category: "navigation", strategy: "modal-escape", ownerScope: "page", prepare: { action: "click", role: "button", name: "打开命令面板" } },
  { exportName: "ConfirmDialog", family: "dialog", category: "overlay", strategy: "modal-escape", ownerName: "Dialog", ownerScope: "page", prepare: { action: "click", role: "button", name: "删除项目" } },
  { exportName: "ContextMenu", family: "menu", category: "navigation", strategy: "open-close", key: "Shift+F10" },
  { exportName: "CreateEditPage", family: "create-edit", category: "pattern", strategy: "tab" },
  { exportName: "DataTable", family: "data-table", category: "data", strategy: "toggle", targetSelector: "input[type='checkbox']" },
  { exportName: "DateField", family: "date-time", category: "input", strategy: "tab", targetSelector: "input:not([readonly]):not(:disabled)" },
  { exportName: "DateRangeField", family: "date-time", category: "input", strategy: "tab", targetSelector: "input:not(:disabled)" },
  { exportName: "DetailPage", family: "detail", category: "pattern", strategy: "tab" },
  { exportName: "Dialog", family: "dialog", category: "overlay", strategy: "modal-escape", ownerScope: "page", prepare: { action: "click", role: "button", name: "编辑项目" } },
  { exportName: "DragDrop", family: "drag", category: "actions", strategy: "native-activate", targetRole: "button" },
  { exportName: "Drawer", family: "drawer", category: "overlay", strategy: "modal-escape", ownerScope: "page", prepare: { action: "click", role: "button", name: "打开成员详情" } },
  { exportName: "DropdownMenu", family: "menu", category: "navigation", strategy: "open-close", targetSelector: "button:not(:disabled)" },
  { exportName: "ExpandableText", family: "overflow", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "FamilyLoginPage", family: "authentication", category: "pattern", strategy: "tab" },
  { exportName: "FileUpload", family: "upload", category: "input", strategy: "tab", targetSelector: "button:not(:disabled)" },
  { exportName: "FilterBar", family: "filter-bar", category: "actions", strategy: "tab" },
  { exportName: "FocusTrap", family: "focus-trap", category: "foundation", strategy: "tab" },
  { exportName: "Form", family: "form", category: "input", strategy: "tab" },
  { exportName: "Gallery", family: "gallery", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "GuidedTour", family: "tour", category: "overlay", strategy: "modal-escape", ownerScope: "page", prepare: { action: "click", role: "button", name: "开始引导" } },
  { exportName: "HoverCard", family: "hover-card", category: "overlay", strategy: "focus-popup" },
  { exportName: "IconButton", family: "icon-button", category: "actions", strategy: "native-activate" },
  { exportName: "ImportExportPage", family: "import-export", category: "pattern", strategy: "tab" },
  { exportName: "InfiniteScroll", family: "infinite-scroll", category: "navigation", strategy: "native-activate", targetRole: "button" },
  { exportName: "InlineEdit", family: "inline-edit", category: "input", strategy: "native-activate", targetRole: "button" },
  { exportName: "Input", family: "text-input", category: "input", strategy: "type", targetSelector: "input:not(:disabled):not([readonly])" },
  { exportName: "Lightbox", family: "lightbox", category: "overlay", strategy: "modal-escape", ownerScope: "page", prepare: { action: "click", role: "button", name: "预览图片" } },
  { exportName: "Link", family: "link", category: "actions", strategy: "native-activate" },
  { exportName: "ListManagementPage", family: "list-filter", category: "pattern", strategy: "tab" },
  { exportName: "LoadMore", family: "load-more", category: "navigation", strategy: "native-activate", targetRole: "button" },
  { exportName: "MarkdownEditor", family: "markdown-editor", category: "input", strategy: "type", targetRole: "textbox" },
  { exportName: "MasterDetail", family: "master-detail", category: "pattern", strategy: "tab" },
  { exportName: "MemberManagementPage", family: "list-filter", category: "pattern", strategy: "tab", prepare: { action: "click", role: "tab", name: "成员工作流" } },
  { exportName: "Menu", family: "menu", category: "navigation", strategy: "native-activate" },
  { exportName: "MultiSelect", family: "multi-select", category: "input", strategy: "open-close", key: "Enter", targetRole: "combobox" },
  { exportName: "NumberInput", family: "number", category: "input", strategy: "arrow-change", key: "ArrowUp", targetRole: "spinbutton" },
  { exportName: "OtpInput", family: "otp", category: "input", strategy: "type", key: "7", targetSelector: "input:nth-of-type(3):not(:disabled)" },
  { exportName: "OverflowText", family: "overflow", category: "data", strategy: "focus-popup" },
  { exportName: "PageHeading", family: "list-filter", category: "pattern", strategy: "tab", prepare: { action: "click", role: "tab", name: "页头" } },
  { exportName: "Pagination", family: "pagination", category: "navigation", strategy: "native-activate", targetRole: "button" },
  { exportName: "PasswordInput", family: "text-input", category: "input", strategy: "type", targetSelector: "input[type='password']" },
  { exportName: "Popconfirm", family: "popconfirm", category: "overlay", strategy: "open-close", key: "Enter", ownerName: "Popover", ownerScope: "page", prepare: { action: "click", role: "button", name: "确认移除成员" }, targetRole: "button", targetName: "确认移除成员" },
  { exportName: "Popover", family: "popover", category: "overlay", strategy: "open-close", key: "Enter", targetRole: "button", targetName: "筛选摘要" },
  { exportName: "Radio", family: "radio", category: "input", strategy: "toggle", targetSelector: "input[type='radio']:not(:disabled)" },
  { exportName: "Rating", family: "rating", category: "input", strategy: "native-activate", targetRole: "radio" },
  { exportName: "ResizablePanels", family: "resizable", category: "foundation", strategy: "arrow-change", key: "ArrowRight", targetRole: "separator" },
  { exportName: "RetryButton", family: "result", category: "feedback", strategy: "native-activate" },
  { exportName: "RichTextEditor", family: "markdown-editor", category: "input", strategy: "type", targetSelector: "textarea:not(:disabled):not([readonly])" },
  { exportName: "Scheduler", family: "scheduler", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "SearchableSelect", family: "select", category: "input", strategy: "open-close", targetRole: "combobox" },
  { exportName: "SearchFilterPage", family: "list-filter", category: "pattern", strategy: "tab", prepare: { action: "click", role: "tab", name: "搜索筛选" } },
  { exportName: "SearchInput", family: "search-input", category: "input", strategy: "type", targetSelector: "input:not(:disabled)" },
  { exportName: "SegmentedControl", family: "segmented", category: "input", strategy: "toggle", targetRole: "button", targetName: "看板" },
  { exportName: "Select", family: "select", category: "input", strategy: "open-close", targetRole: "combobox" },
  { exportName: "SettingsPage", family: "settings", category: "pattern", strategy: "tab" },
  { exportName: "SideNavigation", family: "app-navigation", category: "navigation", strategy: "native-activate" },
  { exportName: "Slider", family: "slider", category: "input", strategy: "arrow-change", key: "ArrowRight", targetRole: "slider" },
  { exportName: "SortableList", family: "sortable", category: "actions", strategy: "native-activate", targetSelector: "button:not(:disabled)" },
  { exportName: "SplitButton", family: "split-button", category: "actions", strategy: "native-activate", targetRole: "button" },
  { exportName: "StatusPage", family: "status-page", category: "pattern", strategy: "tab" },
  { exportName: "Stepper", family: "stepper", category: "navigation", strategy: "native-activate", targetRole: "button" },
  { exportName: "Switch", family: "switch", category: "input", strategy: "toggle", targetSelector: "input[type='checkbox']" },
  { exportName: "Tabs", family: "tabs", category: "navigation", strategy: "arrow-change", key: "ArrowRight", targetRole: "tab" },
  { exportName: "Tag", family: "tag", category: "data", strategy: "native-activate", targetRole: "button", ownerSelector: ".demo-explorer-preview [data-pui-owner='Tag']:has(button)" },
  { exportName: "TagInput", family: "tag-input", category: "input", strategy: "type", targetRole: "combobox" },
  { exportName: "Textarea", family: "textarea", category: "input", strategy: "type", targetSelector: "textarea:not(:disabled):not([readonly])" },
  { exportName: "TimezoneSelect", family: "date-time", category: "input", strategy: "open-close", targetRole: "combobox" },
  { exportName: "ToastProvider", family: "toast", category: "feedback", strategy: "native-activate", ownerScope: "page", prepare: { action: "click", role: "button", name: "居中成功提示" }, targetRole: "button" },
  { exportName: "ToggleButton", family: "toggle-button", category: "actions", strategy: "toggle" },
  { exportName: "Toolbar", family: "toolbar", category: "actions", strategy: "tab" },
  { exportName: "Tooltip", family: "tooltip", category: "overlay", strategy: "focus-popup" },
  { exportName: "TopNavigation", family: "app-navigation", category: "navigation", strategy: "native-activate" },
  { exportName: "Transfer", family: "transfer", category: "input", strategy: "tab" },
  { exportName: "Tree", family: "tree", category: "data", strategy: "arrow-change", key: "ArrowRight", targetRole: "treeitem" },
  { exportName: "TreeSelect", family: "tree-select", category: "input", strategy: "open-close", targetRole: "combobox" },
  { exportName: "TreeTable", family: "data-table", category: "data", strategy: "native-activate", targetRole: "button" },
  { exportName: "useCommandPaletteShortcut", family: "command", category: "navigation", strategy: "shortcut", ownerName: "CommandPalette", ownerScope: "page", prepare: { action: "shortcut", key: "Control+k" } },
  { exportName: "ValidationSummary", family: "validation-summary", category: "feedback", strategy: "native-activate", targetRole: "button" },
  { exportName: "WizardFlow", family: "wizard", category: "pattern", strategy: "tab" },
] as const satisfies readonly KeyboardEvidenceCase[];

registerKeyboardEvidence(keyboardEvidenceCases);
